version: '3.8'
services:
  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./public:/var/www/html

  nginx:
    depends_on:
      - php
    build: ./nginx
    container_name: nginx
    volumes:
      - ./public:/var/www/html
    ports:
      - "80:80"
  
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "10777:80"
    environment:
      PMA_HOST: 'mysql:3306'
      PMA_USER: test # root ou test (s贸 mude ap贸s primeiro build se desejar criar novos bancos)
      PMA_PASSWORD: test # root ou test (s贸 mude ap贸s primeiro build se desejar criar novos bancos)
    
volumes:
  db_data: {}
